services:
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=image_moderation
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - ADMIN_TOKEN=admin-token-here
    depends_on:
      - mongodb

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 
